export const upgradesSpace = {
    stardust: {
        name: "Stardust",
        emoji: "⭐",
        cost: 1500,
        bps: 15,
        bpc: 0,
        owned: 0,
        unlockLevel: 1,
        desc: "Cosmic dust that spontaneously forms into beans.",
    },
    moonrock: {
        name: "Moon Rock",
        emoji: "🌙",
        cost: 3500,
        bps: 0,
        bpc: 30,
        owned: 0,
        unlockLevel: 1,
        desc: "Each chunk you chip off reveals a bean inside.",
    },
    solararray: {
        name: "Solar Array",
        emoji: "🌞",
        cost: 15000,
        bps: 120,
        bpc: 0,
        owned: 0,
        unlockLevel: 3,
        desc: "Converts starlight directly into bean energy.",
    },
    aliencontact: {
        name: "Alien Contact",
        emoji: "👽",
        cost: 35000,
        bps: 0,
        bpc: 200,
        owned: 0,
        unlockLevel: 5,
        desc: "They came from across the galaxy. They brought beans.",
    },
    nebulafarm: {
        name: "Nebula Farm",
        emoji: "🌫️",
        cost: 100000,
        bps: 500,
        bpc: 0,
        owned: 0,
        unlockLevel: 8,
        desc: "Gas clouds seeded with bean spores. Harvest cycle: 1 second.",
    },
    cometcrash: {
        name: "Comet Crash",
        emoji: "☄️",
        cost: 250000,
        bps: 0,
        bpc: 800,
        owned: 0,
        unlockLevel: 10,
        desc: "Redirect comets into your stockpile. Surprisingly beany.",
    },
    spacestation: {
        name: "Space Station",
        emoji: "🛰️",
        cost: 800000,
        bps: 2500,
        bpc: 0,
        owned: 0,
        unlockLevel: 13,
        desc: "Orbiting bean processing facility. Zero gravity = more beans somehow.",
    },
    blackholeextractor: {
        name: "Black Hole Extractor",
        emoji: "🌀",
        cost: 2500000,
        bps: 0,
        bpc: 5000,
        owned: 0,
        unlockLevel: 16,
        desc: "Siphons beans from the event horizon. Very dangerous. Very worth it.",
    },
    pulsarbeacon: {
        name: "Pulsar Beacon",
        emoji: "📡",
        cost: 8000000,
        bps: 15000,
        bpc: 0,
        owned: 0,
        unlockLevel: 20,
        desc: "Broadcasts bean-growth signals across the galaxy at light speed.",
    },
    wormhole: {
        name: "Wormhole",
        emoji: "🕳️",
        cost: 25000000,
        bps: 0,
        bpc: 40000,
        owned: 0,
        unlockLevel: 24,
        desc: "Each click pulls beans from a parallel universe where beans are everything.",
    },
    dysonshell: {
        name: "Dyson Shell",
        emoji: "🔆",
        cost: 100000000,
        bps: 200000,
        bpc: 0,
        owned: 0,
        unlockLevel: 29,
        desc: "Encases an entire star. All that energy, converted to beans.",
    },
    quantumtunnel: {
        name: "Quantum Tunnel",
        emoji: "🔬",
        cost: 350000000,
        bps: 0,
        bpc: 3000000,
        owned: 0,
        unlockLevel: 34,
        desc: "Beans tunnel through spacetime directly into your count.",
    },
    galaxycore: {
        name: "Galaxy Core",
        emoji: "💫",
        cost: 2000000000,
        bps: 15000000,
        bpc: 0,
        owned: 0,
        unlockLevel: 40,
        desc: "The supermassive bean at the center of everything.",
    },
    cosmicstring: {
        name: "Cosmic String",
        emoji: "🧵",
        cost: 15000000000,
        bps: 0,
        bpc: 100000000,
        owned: 0,
        unlockLevel: 47,
        desc: "A one-dimensional defect in spacetime, vibrating at bean frequency.",
    },
    universalseed: {
        name: "Universal Seed",
        emoji: "🌌",
        cost: 80000000000,
        bps: 500000000,
        bpc: 500000000,
        owned: 0,
        unlockLevel: 55,
        desc: "The origin of all cosmic beans. It was there at the Big Bean.",
    },
};