// upgrades-lava.js — Lava Bean world upgrades (prestige 2+)
// Mix of volcanic, demonic, and industrial flavor
// Costs scale up from where space upgrades left off

export const upgradesLava = {
    magmapool: {
        name: "Magma Pool",
        emoji: "🌋",
        cost: 2000,
        bps: 8,
        bpc: 0,
        owned: 0,
        unlockLevel: 1,
        desc: "A bubbling pool of magma. Beans form in the cooling crust.",
    },
    ashsifter: {
        name: "Ash Sifter",
        emoji: "🌫️",
        cost: 4500,
        bps: 0,
        bpc: 12,
        owned: 0,
        unlockLevel: 1,
        desc: "Sift through volcanic ash after each eruption. Rich in beans.",
    },
    lavaforge: {
        name: "Lava Forge",
        emoji: "⚒️",
        cost: 14000,
        bps: 45,
        bpc: 0,
        owned: 0,
        unlockLevel: 3,
        desc: "Industrial forge powered entirely by the earth's core. Never cools.",
    },
    demonpact: {
        name: "Demon Pact",
        emoji: "😈",
        cost: 32000,
        bps: 0,
        bpc: 75,
        owned: 0,
        unlockLevel: 5,
        desc: "You sold your soul. In return, demons deliver beans on every click.",
    },
    obsidianmine: {
        name: "Obsidian Mine",
        emoji: "⛏️",
        cost: 90000,
        bps: 180,
        bpc: 0,
        owned: 0,
        unlockLevel: 8,
        desc: "Deep obsidian veins hide pockets of compressed beans. Worth every drill.",
    },
    hellgate: {
        name: "Hell Gate",
        emoji: "🔥",
        cost: 220000,
        bps: 0,
        bpc: 350,
        owned: 0,
        unlockLevel: 10,
        desc: "A direct portal to the underworld. Beans pour through constantly.",
    },
    volcanicvent: {
        name: "Volcanic Vent",
        emoji: "💨",
        cost: 650000,
        bps: 900,
        bpc: 0,
        owned: 0,
        unlockLevel: 13,
        desc: "Superheated vents launch beans skyward at 200mph. Catch them all.",
    },
    cursedcauldron: {
        name: "Cursed Cauldron",
        emoji: "🫕",
        cost: 1600000,
        bps: 0,
        bpc: 2000,
        owned: 0,
        unlockLevel: 16,
        desc: "Stir the cauldron. Each click multiplies the beans within. Cursed? Maybe.",
    },
    moltensmelter: {
        name: "Molten Smelter",
        emoji: "🏭",
        cost: 5000000,
        bps: 4000,
        bpc: 0,
        owned: 0,
        unlockLevel: 20,
        desc: "Industrial-scale smelting operation. Ore goes in, beans come out.",
    },
    infernalpress: {
        name: "Infernal Press",
        emoji: "🗜️",
        cost: 12000000,
        bps: 0,
        bpc: 8500,
        owned: 0,
        unlockLevel: 24,
        desc: "Demonic hydraulic press. Compresses raw hellstone into pure bean ingots.",
    },
    eruption: {
        name: "Mass Eruption",
        emoji: "🌋",
        cost: 38000000,
        bps: 18000,
        bpc: 0,
        owned: 0,
        unlockLevel: 29,
        desc: "Trigger a controlled eruption on demand. Beans rain from the sky for days.",
    },
    soulharvester: {
        name: "Soul Harvester",
        emoji: "💀",
        cost: 95000000,
        bps: 0,
        bpc: 40000,
        owned: 0,
        unlockLevel: 34,
        desc: "Every soul that enters the underworld carries a bean tithe. Collect them all.",
    },
    tectonicshift: {
        name: "Tectonic Shift",
        emoji: "🌍",
        cost: 300000000,
        bps: 90000,
        bpc: 0,
        owned: 0,
        unlockLevel: 40,
        desc: "Shift the tectonic plates to expose ancient bean deposits miles underground.",
    },
    demonlord: {
        name: "Demon Lord",
        emoji: "👹",
        cost: 800000000,
        bps: 0,
        bpc: 220000,
        owned: 0,
        unlockLevel: 47,
        desc: "You command a demon lord. His armies farm beans across seventeen dimensions of hell.",
    },
    coreoftheearth: {
        name: "Core of the Earth",
        emoji: "🔴",
        cost: 2500000000,
        bps: 600000,
        bpc: 600000,
        owned: 0,
        unlockLevel: 55,
        desc: "You've drilled to the earth's core. It's beans all the way down.",
    },
};