// upgrades-lava.js — Lava Bean world upgrades (prestige 2+)
// Scales up to level 200 (max level at prestige 2)
// Stronger than Space at every tier

export const upgradesLava = {
    magmapool: {
        name: "Magma Pool",
        emoji: "🌋",
        cost: 5000,
        bps: 40,
        bpc: 0,
        owned: 0,
        unlockLevel: 1,
        desc: "A bubbling pool of magma. Beans form in the cooling crust.",
    },
    ashsifter: {
        name: "Ash Sifter",
        emoji: "🌫️",
        cost: 12000,
        bps: 0,
        bpc: 70,
        owned: 0,
        unlockLevel: 1,
        desc: "Sift through volcanic ash after each eruption. Rich in beans.",
    },
    lavaforge: {
        name: "Lava Forge",
        emoji: "⚒️",
        cost: 50000,
        bps: 300,
        bpc: 0,
        owned: 0,
        unlockLevel: 5,
        desc: "Industrial forge powered entirely by the earth's core. Never cools.",
    },
    demonpact: {
        name: "Demon Pact",
        emoji: "😈",
        cost: 120000,
        bps: 0,
        bpc: 500,
        owned: 0,
        unlockLevel: 8,
        desc: "You sold your soul. In return, demons deliver beans on every click.",
    },
    obsidianmine: {
        name: "Obsidian Mine",
        emoji: "⛏️",
        cost: 400000,
        bps: 1500,
        bpc: 0,
        owned: 0,
        unlockLevel: 12,
        desc: "Deep obsidian veins hide pockets of compressed beans. Worth every drill.",
    },
    hellgate: {
        name: "Hell Gate",
        emoji: "🔥",
        cost: 1200000,
        bps: 0,
        bpc: 3000,
        owned: 0,
        unlockLevel: 16,
        desc: "A direct portal to the underworld. Beans pour through constantly.",
    },
    volcanicvent: {
        name: "Volcanic Vent",
        emoji: "💨",
        cost: 4000000,
        bps: 8000,
        bpc: 0,
        owned: 0,
        unlockLevel: 20,
        desc: "Superheated vents launch beans skyward at 200mph. Catch them all.",
    },
    cursedcauldron: {
        name: "Cursed Cauldron",
        emoji: "🫕",
        cost: 15000000,
        bps: 0,
        bpc: 20000,
        owned: 0,
        unlockLevel: 25,
        desc: "Stir the cauldron. Each click multiplies the beans within. Cursed? Maybe.",
    },
    moltensmelter: {
        name: "Molten Smelter",
        emoji: "🏭",
        cost: 50000000,
        bps: 80000,
        bpc: 0,
        owned: 0,
        unlockLevel: 30,
        desc: "Industrial-scale smelting operation. Ore goes in, beans come out.",
    },
    infernalpress: {
        name: "Infernal Press",
        emoji: "🗜️",
        cost: 200000000,
        bps: 0,
        bpc: 500000,
        owned: 0,
        unlockLevel: 35,
        desc: "Demonic hydraulic press. Compresses raw hellstone into pure bean ingots.",
    },
    eruption: {
        name: "Mass Eruption",
        emoji: "🌋",
        cost: 800000000,
        bps: 5000000,
        bpc: 0,
        owned: 0,
        unlockLevel: 40,
        desc: "Trigger a controlled eruption on demand. Beans rain from the sky for days.",
    },
    soulharvester: {
        name: "Soul Harvester",
        emoji: "💀",
        cost: 5000000000,
        bps: 0,
        bpc: 30000000,
        owned: 0,
        unlockLevel: 47,
        desc: "Every soul that enters the underworld carries a bean tithe. Collect them all.",
    },
    tectonicshift: {
        name: "Tectonic Shift",
        emoji: "🌍",
        cost: 30000000000,
        bps: 200000000,
        bpc: 0,
        owned: 0,
        unlockLevel: 55,
        desc: "Shift the tectonic plates to expose ancient bean deposits miles underground.",
    },
    demonlord: {
        name: "Demon Lord",
        emoji: "👹",
        cost: 200000000000,
        bps: 0,
        bpc: 1500000000,
        owned: 0,
        unlockLevel: 63,
        desc: "You command a demon lord. His armies farm beans across seventeen dimensions of hell.",
    },
    coreoftheearth: {
        name: "Core of the Earth",
        emoji: "🔴",
        cost: 1500000000000,
        bps: 8000000000,
        bpc: 8000000000,
        owned: 0,
        unlockLevel: 70,
        desc: "You've drilled to the earth's core. It's beans all the way down.",
    },

    // ── Extended upgrades (levels 78-200) ──

    ashstorm: {
        name: "Ash Storm",
        emoji: "🌪️",
        cost: 8000000000000,
        bps: 50000000000,
        bpc: 0,
        owned: 0,
        unlockLevel: 78,
        desc: "A planet-wide storm of volcanic ash. Every grain carries a bean seed.",
    },
    bloodforge: {
        name: "Blood Forge",
        emoji: "🩸",
        cost: 40000000000000,
        bps: 0,
        bpc: 200000000000,
        owned: 0,
        unlockLevel: 86,
        desc: "Forged with sacrificial fire. Each click draws beans from the veins of the earth.",
    },
    mantleripper: {
        name: "Mantle Ripper",
        emoji: "⚡",
        cost: 250000000000000,
        bps: 300000000000,
        bpc: 0,
        owned: 0,
        unlockLevel: 95,
        desc: "Tears the planet's mantle open. The bean deposits underneath are incomprehensible.",
    },
    hellfiresanctum: {
        name: "Hellfire Sanctum",
        emoji: "🏛️",
        cost: 1500000000000000,
        bps: 0,
        bpc: 1200000000000,
        owned: 0,
        unlockLevel: 104,
        desc: "A temple built inside an active volcano. Every prayer yields a billion beans.",
    },
    doomcaldera: {
        name: "Doom Caldera",
        emoji: "🕳️",
        cost: 10000000000000000,
        bps: 2000000000000,
        bpc: 0,
        owned: 0,
        unlockLevel: 113,
        desc: "A caldera so vast it has its own weather system. It rains beans.",
    },
    titanslayer: {
        name: "Titan Slayer",
        emoji: "⚔️",
        cost: 60000000000000000,
        bps: 0,
        bpc: 8000000000000,
        owned: 0,
        unlockLevel: 122,
        desc: "Slay fire titans. Their corpses decompose into pure concentrated bean matter.",
    },
    worldeater: {
        name: "World Eater",
        emoji: "🐉",
        cost: 400000000000000000,
        bps: 15000000000000,
        bpc: 0,
        owned: 0,
        unlockLevel: 130,
        desc: "An ancient serpent that devours planets and excretes beans. You ride it.",
    },
    infernalengine: {
        name: "Infernal Engine",
        emoji: "⚙️",
        cost: 3000000000000000000,
        bps: 0,
        bpc: 50000000000000,
        owned: 0,
        unlockLevel: 140,
        desc: "A machine that runs on damned souls. Its exhaust is pure bean vapor.",
    },
    ragnarok: {
        name: "Ragnarök",
        emoji: "☠️",
        cost: 20000000000000000000,
        bps: 100000000000000,
        bpc: 0,
        owned: 0,
        unlockLevel: 150,
        desc: "The end of all worlds. Fire consumes everything. Only beans remain.",
    },
    hellthroneascended: {
        name: "Hell Throne",
        emoji: "🪑",
        cost: 150000000000000000000,
        bps: 0,
        bpc: 400000000000000,
        owned: 0,
        unlockLevel: 160,
        desc: "You sit upon the throne of Hell. Every demon in existence farms beans for you.",
    },
    abyssalrift: {
        name: "Abyssal Rift",
        emoji: "🌊",
        cost: 1000000000000000000000,
        bps: 800000000000000,
        bpc: 0,
        owned: 0,
        unlockLevel: 170,
        desc: "A rift to the abyss below Hell. Even demons fear what lives there. It makes beans.",
    },
    primordialflame: {
        name: "Primordial Flame",
        emoji: "🔥",
        cost: 8000000000000000000000,
        bps: 0,
        bpc: 3000000000000000,
        owned: 0,
        unlockLevel: 180,
        desc: "The first fire that ever burned. It has been making beans since before time.",
    },
    souloftheplanet: {
        name: "Soul of the Planet",
        emoji: "💎",
        cost: 60000000000000000000000,
        bps: 5000000000000000,
        bpc: 0,
        owned: 0,
        unlockLevel: 190,
        desc: "You consumed the planet's soul. Its entire existence is now bean production.",
    },
    eternalpyre: {
        name: "Eternal Pyre",
        emoji: "🔱",
        cost: 500000000000000000000000,
        bps: 20000000000000000,
        bpc: 20000000000000000,
        owned: 0,
        unlockLevel: 198,
        desc: "A fire that cannot be extinguished. It burns across dimensions. Everything it touches becomes beans.",
    },
};