export const upgradesSpace = {
    stardust: {
        name: "Stardust",
        emoji: "⭐",
        cost: 500,
        bps: 3,
        bpc: 0,
        owned: 0,
        unlockLevel: 1,
        desc: "Cosmic dust that spontaneously forms into beans.",
    },
    moonrock: {
        name: "Moon Rock",
        emoji: "🌙",
        cost: 1000,
        bps: 0,
        bpc: 5,
        owned: 0,
        unlockLevel: 1,
        desc: "Each chunk you chip off reveals a bean inside.",
    },
    solararray: {
        name: "Solar Array",
        emoji: "🌞",
        cost: 4000,
        bps: 20,
        bpc: 0,
        owned: 0,
        unlockLevel: 3,
        desc: "Converts starlight directly into bean energy.",
    },
    aliencontact: {
        name: "Alien Contact",
        emoji: "👽",
        cost: 9000,
        bps: 0,
        bpc: 35,
        owned: 0,
        unlockLevel: 5,
        desc: "They came from across the galaxy. They brought beans.",
    },
    nebulafarm: {
        name: "Nebula Farm",
        emoji: "🌫️",
        cost: 28000,
        bps: 90,
        bpc: 0,
        owned: 0,
        unlockLevel: 8,
        desc: "Gas clouds seeded with bean spores. Harvest cycle: 1 second.",
    },
    cometcrash: {
        name: "Comet Crash",
        emoji: "☄️",
        cost: 60000,
        bps: 0,
        bpc: 120,
        owned: 0,
        unlockLevel: 10,
        desc: "Redirect comets into your stockpile. Surprisingly beany.",
    },
    spacestation: {
        name: "Space Station",
        emoji: "🛰️",
        cost: 180000,
        bps: 320,
        bpc: 0,
        owned: 0,
        unlockLevel: 13,
        desc: "Orbiting bean processing facility. Zero gravity = more beans somehow.",
    },
    blackholeextractor: {
        name: "Black Hole Extractor",
        emoji: "🌀",
        cost: 450000,
        bps: 0,
        bpc: 600,
        owned: 0,
        unlockLevel: 16,
        desc: "Siphons beans from the event horizon. Very dangerous. Very worth it.",
    },
    pulsarbeacon: {
        name: "Pulsar Beacon",
        emoji: "📡",
        cost: 1200000,
        bps: 1100,
        bpc: 0,
        owned: 0,
        unlockLevel: 20,
        desc: "Broadcasts bean-growth signals across the galaxy at light speed.",
    },
    wormhole: {
        name: "Wormhole",
        emoji: "🕳️",
        cost: 3000000,
        bps: 0,
        bpc: 2200,
        owned: 0,
        unlockLevel: 24,
        desc: "Each click pulls beans from a parallel universe where beans are everything.",
    },
    dysonshell: {
        name: "Dyson Shell",
        emoji: "🔆",
        cost: 9000000,
        bps: 4500,
        bpc: 0,
        owned: 0,
        unlockLevel: 29,
        desc: "Encases an entire star. All that energy, converted to beans.",
    },
    quantumtunnel: {
        name: "Quantum Tunnel",
        emoji: "🔬",
        cost: 22000000,
        bps: 0,
        bpc: 9000,
        owned: 0,
        unlockLevel: 34,
        desc: "Beans tunnel through spacetime directly into your count.",
    },
    galaxycore: {
        name: "Galaxy Core",
        emoji: "💫",
        cost: 70000000,
        bps: 20000,
        bpc: 0,
        owned: 0,
        unlockLevel: 40,
        desc: "The supermassive bean at the center of everything.",
    },
    cosmicstring: {
        name: "Cosmic String",
        emoji: "🧵",
        cost: 180000000,
        bps: 0,
        bpc: 50000,
        owned: 0,
        unlockLevel: 47,
        desc: "A one-dimensional defect in spacetime, vibrating at bean frequency.",
    },
    universalseed: {
        name: "Universal Seed",
        emoji: "🌌",
        cost: 600000000,
        bps: 120000,
        bpc: 120000,
        owned: 0,
        unlockLevel: 55,
        desc: "The origin of all cosmic beans. It was there at the Big Bean.",
    },
};